//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBDIntegrationWorker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=omi6dwwsxk.database.windows.net;Initial Catalog=SynchDevelopmentDB2;P" +
            "ersist Security Info=True;User ID=smladmin;Password=SCANmyLIST2012;Max Pool Size" +
            "=2000")]
        public string SynchDevelopmentDB2ConnectionString {
            get {
                return ((string)(this["SynchDevelopmentDB2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=omi6dwwsxk.database.windows.net;Initial Catalog=SynchTestDB;Persist S" +
            "ecurity Info=True;User ID=smladmin;Password=SCANmyLIST2012")]
        public string SynchTestDBConnectionString {
            get {
                return ((string)(this["SynchTestDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=omi6dwwsxk.database.windows.net;Initial Catalog=SynchProductionDB1;Us" +
            "er ID=smladmin;Password=SCANmyLIST2012")]
        public string SynchProductionDB1ConnectionString {
            get {
                return ((string)(this["SynchProductionDB1ConnectionString"]));
            }
        }
    }
}
